name: sdlm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.0
  - cudatoolkit=11.3
  - pip
  - pip:
      - sacremoses
      - rouge_score
      - accelerate==0.12.0
      - ipython==8.4.0
      - tensorboard==2.9.1
      - datasets==2.14.6
      - transformers==4.25.1
      - diffusers==v0.7.2
      - huggingface_hub==0.14.0
      - torchvision==0.13.0
      - torchaudio==0.12.0
      - scipy==1.9.3
      - scikit-learn==1.2.2
      - pyarrow==10.0.1
      - nltk
      - sentencepiece
      - sacrebleu
      - evaluate
      - bert_score
